loglevel: "debug"
ICEServers:
  - "stun:stun.l.google.com:19302"
signallingserver: "wss://roundtablesignallingserver.fly.dev/ws"
timeout: 30
OPUSFrameDuration: "60ms"
OPUSBufferSafetyFactor: 16
codecs:
  - "CodecOpus48000Mono"
