.PHONY: playaudiofile recordaudiofile

repl:
	go run main.go
recordaudiofile:
	go run main.go -mode=record -file="../../assets/media.wav"
playaudiofile:
	go run main.go -mode=play -file="../../assets/media.wav"
